### PR TITLE
22.08 update

### PR DESCRIPTION
**Pull request by orowith2os**
X86-only for now, until upstream provides arm64 binaries for 0.10.0.

### CODE REVIEW

**Comment by orowith2os** [comment]
bot, build io.github.Figma_Linux.figma_linux

**Comment by orowith2os** [comment]
@hfiguiere would you be okay with force-merging this? It only seems to fail on the data checker.

**Comment by hfiguiere** [comment]
it won't build either. It's the exact same thing.

**Comment by hfiguiere** [comment]
Two solution
1. remove the f-e-d-c for aarch64 until there is a build
2. build from source.

**Comment by orowith2os** [comment]
I'll go for number two (2), I should be able to open up a working terminal tomorrow.

**Comment by orowith2os** [comment]
Turns out I've gotten myself into some other stuff way too quickly, I'll just go with x86-only builds.

**Comment by orowith2os** [comment]
@hfiguiere wanna merge it? I'm not sure if @ChugunovRoman is maintaining this much any more, it would be appreciated if I could assist in keeping it up to date as well.

**Pull request merged**
